name: spendwise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Current stable versions
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6

  # State Management
  provider: ^6.1.1
  http: ^1.2.0
  path_provider: ^2.1.2
  package_info_plus: ^5.0.1
  android_intent_plus: ^4.0.3
  device_info_plus: ^9.1.2
  permission_handler: ^11.3.1


  # UI & Utils
  cupertino_icons: ^1.0.8
  uuid: ^4.2.1
  intl: ^0.19.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.2
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0

  # Notification dependencies - SIMPLIFIED APPROACH
  firebase_messaging: ^14.7.6
  # awesome_notifications: ^0.9.3+1  # Temporarily disabled - causing issues
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#3B82F6"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/